# Generated by Django 5.2.5 on 2025-08-22 09:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OmeroUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('omero_password', models.CharField(help_text='The password for the omero user', max_length=2000)),
                ('omero_username', models.CharField(help_text='The username for the omero user', max_length=2000)),
                ('omero_host', models.CharField(default='omero', help_text='The host for the omero user', max_length=2000)),
                ('omero_port', models.IntegerField(default=4064, help_text='The port for the omero user')),
                ('user', models.ForeignKey(help_text='The user that created the dataset', on_delete=django.db.models.deletion.CASCADE, related_name='omero_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
