# Generated by Django 4.2.9 on 2024-01-30 14:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("bridge", "0002_omerouser_omero_password_omerouser_omero_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="omerouser",
            name="omero_host",
            field=models.CharField(
                default="omeroserver",
                help_text="The host for the omero user",
                max_length=2000,
            ),
        ),
        migrations.AddField(
            model_name="omerouser",
            name="omero_port",
            field=models.IntegerField(
                default=4064, help_text="The port for the omero user"
            ),
        ),
        migrations.AlterField(
            model_name="omerouser",
            name="user",
            field=models.ForeignKey(
                help_text="The user that created the dataset",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="omero_user",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
